kqueue: fix build on FreeBSD
The kqueue crate supports platform-specific events, so the build was failing on FreeBSD with:
error[E0004]: non-exhaustive patterns: `Open`, `CloseWrite` and `Close` not covered